<?php

namespace AdminBundle\Repository;

/**
 * AnswerAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
