<?php

namespace AdminBundle\Repository;

/**
 * CategoryCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
