<?php

namespace AdminBundle\Repository;

/**
 * FileExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileExamRepository extends \Doctrine\ORM\EntityRepository
{
}
