<?php

namespace AdminBundle\Repository;

/**
 * FinishExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinishExamRepository extends \Doctrine\ORM\EntityRepository
{
}
