<?php

namespace AdminBundle\Repository;

/**
 * FinishExamUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinishExamUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
