<?php

namespace AdminBundle\Repository;

/**
 * InfoCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
