<?php

namespace AdminBundle\Repository;

/**
 * MandatoryReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandatoryReadingRepository extends \Doctrine\ORM\EntityRepository
{
}
