<?php

namespace AdminBundle\Repository;

/**
 * QuestionAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
