<?php

namespace AdminBundle\Repository;

/**
 * SupplementaryReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementaryReadingRepository extends \Doctrine\ORM\EntityRepository
{
}
