<?php

namespace AdminBundle\Repository;

/**
 * UploadExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadExamRepository extends \Doctrine\ORM\EntityRepository
{
}
