forgot-password:
    path: /forgot-password
    defaults: { _controller: AdminBundle:Password:forgotPassword} 

checkout-password:
    path: /checkout-password
    defaults: { _controller: AdminBundle:Password:checkoutPassword} 
    
change-password:
    path: /change-password/{id}
    defaults: { _controller: AdminBundle:Password:changePassword, id:null }  
    
success-password:
    path: /success-password
    defaults: { _controller: AdminBundle:Password:successPassword}  